@hostname = http://localhost:3000/api

### séparateur entre deux requêtes

POST {{hostname}}/auth/signup
content-type: application/json

{
	"last_name": "John",
   "first_name": "Doeuf",
   "email": "rouge@doeuf.com",
   "password": "Password123$",
   "gender": "male",
   "role_id": "coworker"
}

### séparateur entre deux requêtes

POST {{hostname}}/auth/login
content-type: application/json

{
   "email": "Anice78@hotmail.fr",
   "password": "password"
}

### séparateur entre deux requêtes

GET {{hostname}}/coworker
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjU3LCJ1c2VyUm9sZURlc2NyaXB0aW9uIjoiY293b3JrZXIiLCJpYXQiOjE2NjQyODM1MzUsImV4cCI6MTY2NDM2OTkzNX0.rMUeUfT0MAMxQcYnBK4npbU9OOia33Juyl8yyTt6N-U

{
   "email": "rouge@doeuf.com",
   "password": "Password123$"
}

### séparateur entre deux requêtes

GET {{hostname}}/personalspace/:id/coworkerbooking
content-type: application/json

### séparateur entre deux requêtes

POST {{hostname}}/booking/request
content-type: application/json

{
   "start-date": "01.01.01",
   "end_date" : "02.02.02",
   "user_id" : 1,
   "workspace_id" : 1
}

### séparateur entre deux requêtes

GET {{hostname}}/personalspace/1/coworkerbooking
content-type: application/json

### séparateur entre deux requêtes

PATCH {{hostname}}/booking/2/state
content-type: application/json

{
   "stateDescription": "En attente"
}